
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: root
  password: <%= ENV["MYSQL_PASSWORD"] %>
  database: sms-api-dev
  host: localhost
  port: 3306


test:
  <<: *default
  username: root
  password: <%= ENV["MYSQL_PASSWORD"] %>
  database: sms-api-test
  host: localhost
  port: 3306

production:
  <<: *default
