
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: localhost
  port: 3306

development:
  <<: *default
  database: sms-api-dev

test:
  <<: *default
  database: sms-api-test

production:
  <<: *default
  database: sms-api-prod
